'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert('IPAs', [
      {
        userId: 1,
        name: 'Sweet Water IPA',
        imageUrl: 'https://www.sweetwaterbrew.com/wp-content/uploads/IPA-silo.png',
        brewery: 'Sweet Water Brewing Company',
        breweryLink: 'https://www.sweetwaterbrew.com/',
        description: 'This mammoth IPA is defined by generous quantities of juicy American hops. The extensive dry hopping process contributes to its bright and flavorful character. This beer is unfiltered to leave all the natural flavors intact and bottle conditioned to stay super fresh.',
        country: 'United States of America',
        rating: 6,
        ABV: 6.3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Brouwerij\'tij IPA',
        imageUrl: 'https://www.brouwerijhetij.nl/wp-content/uploads/2021/03/IPA_Table-card_Artwork_20.1-960x1269.jpg',
        brewery: 'Brouwerij\'tij',
        breweryLink: 'https://www.brouwerijhetij.nl/flink/',
        description: 'Our I.P.A. is a dark blonde beer with a distinct hop flavor. The abbreviation stands for India Pale Ale. This is an original English beer style that came about when the English ales were given a higher alcohol percentage and firmer hop recipe. This way they survived the ship voyage to the colonies better. In our I.P.A., we added hops to the beer not only during brewing, but also during aging. This creates delicious aromas of grapefruit and flowers. A beer with a fruity, bitter aftertaste that lingers for a long time.',
        country: 'Netherlands',
        rating: 5.5,
        ABV: 6.5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Taras Boulba',
        imageUrl: 'https://cdn.beeradvocate.com/im/c_beer_image.gif',
        brewery: 'Brasserie de la Senne',
        breweryLink: 'https://www.brasseriedelasenne.be/?lang=fr',
        description: 'Light blonde with 4.5% alc., generously hopped with the finest aromatic hops, giving it a very refreshing character and a scent reminiscent of citrus.',
        country: 'France',
        rating: 5.5,
        ABV: 4.5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Lowlander I.P.A.',
        imageUrl: 'https://cdn.beeradvocate.com/im/c_beer_image.gif',
        brewery: 'Lowlander Botanical Beers',
        breweryLink: 'https://www.lowlander-beer.com/',
        description: 'Brewed with coriander seeds & white tea. Citrusy, hoppy & bitter with refreshing notes of spice.',
        country: 'Neherlands',
        rating: 6.5,
        ABV: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Terminal Pale Ale',
        imageUrl: 'https://www.brewfist.com/wp-content/uploads/2017/07/TPA-1-368x1127-4.png',
        brewery: 'BrewFirst',
        breweryLink: 'https://www.brewfist.com/',
        description: 'The house beer, originally created for our pub here in Codogno: a light, lean and fragrant American Pale Ale. Thin body and soft bitterness, but great freshness and citrusy character thanks to the American Citra hops. Defaticante and accommodating.',
        country: 'Italy',
        rating: 5,
        ABV: 3.7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'IPA (Citra Cryo • Cascade)',
        imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.ONh-J_mfzVmxwTvVStPuogHaJ4%26pid%3DApi&f=1',
        brewery: 'WAZEMMES',
        breweryLink: 'https://www.wzm.beer/',
        description: 'Generously hopped beer with citrus flavors (orange, grapefruit), slightly caramelized and not very bitter. ',
        country: 'Belgium',
        rating: 5,
        ABV: 6.8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Miss Hops',
        imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.uVxGjuU_EYZlimZX2wOWHgAAAA%26pid%3DApi&f=1',
        brewery: 'Barcelona Beer Company',
        breweryLink: 'http://www.barcelonabeercompany.com/en/',
        description: 'Miss Hops is an IPA with lots and lots of Simcoe & Amarillo',
        country: 'Spain',
        rating: 6.5,
        ABV: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: '13 Guns',
        imageUrl: 'https://cdn.beeradvocate.com/im/c_beer_image.gif',
        brewery: 'Daniel Thwaites Brewery PLC',
        breweryLink: 'https://www.houseofdanielthwaites.co.uk/news-and-blog/top-award-for-thwaites-beer/',
        description: 'An Intense Hit of Hops',
        country: 'England',
        rating: 6.5,
        ABV: 5.5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Double Dippy Doo',
        imageUrl: 'https://cdn.shopify.com/s/files/1/0189/2371/6708/products/DOUBLEDIPPYDOO_750x1000.png?v=1614002935',
        brewery: 'Dry & Bitter',
        breweryLink: 'https://dryandbitter.com/',
        description: 'Double Dry-Hopped DIPA with masses of Citra and a touch of Simcoe. Hazy and crushable, lusciously soft, dank and juicy.',
        country: 'Denmark',
        rating: 6.5,
        ABV: 7.5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Fastest Hunk of Junk in the Galaxy',
        imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.IPywB231_38WejJq2ih9HQHaHa%26pid%3DApi&f=1',
        brewery: 'S43 Brewery',
        breweryLink: 'https://s43brewery.com/',
        description: 'Galaxy: Enigma and Galaxy! This smooth and hazy DIPA features big tropical fruit notes along with passionfruit and citrus and a rounded bitterness to keep everything in check. Plenty of malty and juicy sweetness hides the abv well.',
        country: 'England',
        rating: 5,
        ABV: 8.1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Revenge of the Pith',
        imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.9fXf4xWgIStN4y2MWLkBeQHaHa%26pid%3DApi%26h%3D160&f=1',
        brewery: 'S43 Brewery',
        breweryLink: 'https://s43brewery.com/',
        description: 'A classic west coast IPA with tons of old school bitterness with a rounded malt profile. Citrusy and piney hops Cascade, Amarillo and Falconers Flight bring lots of pithy grapefruit notes and a refreshing citrusy zing. Weve added Grapefruit and Blood Orange zest, juice and puree to get the fruity flavours into hyper drive.',
        country: 'England',
        rating: 5.5,
        ABV: 6.7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Jungle Juice',
        imageUrl: 'https://cdn.beeradvocate.com/im/c_beer_image.gif',
        brewery: 'Cervisiam Bryggeri',
        breweryLink: 'https://www.cervisiam.no/',
        description: ' Jungle Juice is an imperial IPA made to emulate a punch in the face by Rambo. It\'s brewed with our favourite hop, Nelson Sauvin, along with considerable doses of other hops lending it a solid tropical-fruity nose. A rich and creamy Imperial IPA.',
        country: 'Norway',
        rating: 5.5,
        ABV: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Reptile Steel',
        imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.RautyWQ-sLzaWeoT8SWxDQHaHa%26pid%3DApi&f=1',
        brewery: 'Steel City Brewing X',
        breweryLink: null,
        description: 'Fruited Sour Ipa with Pineapple and Summit, Chinook & Nelson Sauvin Hops.',
        country: 'Spain',
        rating: 6,
        ABV: 6.3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'A L\'Ouest',
        imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.iaSodswspH2wnCuGgdGKKwHaHa%26pid%3DApi&f=1',
        brewery: 'Brasserie du Grand Paris',
        breweryLink: 'https://www.bgp.paris/',
        description: 'An Americanized version of a Hefeweizen, these beers typically fall between pale straw and deep gold in color. Pale Wheat Ales are reminiscent of a Hefeweizen in appearance, unless filtered. Higher carbonation is proper as is a long-lasting head and a light to medium body. German Weizen flavors and aromas of banana esters and clove-like phenols won\'t be found. Most use a substantial percentage of wheat malt. Hop character could be low or fairly high, but most examples are moderate in bitterness. There may be some fruitiness from ale fermentation though most examples use a fairly neutral ale yeast, resulting in a clean fermentation with little to no diacetyl. Often served with a lemon wedge to either cut the wheat or yeast edge, many people either find this to be a flavorful snap or an insult that damages the beer\'s taste and head retention.',
        country: 'France',
        rating: 6,
        ABV: 4.7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Madame Butterfly',
        imageUrl: 'https://cdn.beeradvocate.com/im/c_beer_image.gif',
        brewery: 'Pühaste Brewery',
        breweryLink: 'https://puhastebeer.com/',
        description: 'Amber ale brewed with Earl Grey tea, American hops (Centennial, Cascade, Willamette) and cornflower blossoms.',
        country: 'Estonia',
        rating: 5.5,
        ABV: 5.6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Bieère IPA',
        imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.g0xUoA8ogLEm1Jsex3H0gwAAAA%26pid%3DApi%26h%3D160&f=1',
        brewery: 'Gustave Artisan Brasseur',
        breweryLink: 'https://www.aucoeurdumalt.com/',
        description: 'A copper-colored beer with a frank fizz and a generous head, a fine malty taste with hoppy, fruity and floral aromas, accompanied by a note of honey dear to Gustave.',
        country: 'France',
        rating: 6,
        ABV: 6.2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Coreff IPA',
        imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.cIfHEvIkeuLGmcd_r6fAjQHaHa%26pid%3DApi&f=1',
        brewery: 'Brassery Coreff',
        breweryLink: 'https://brasserie-coreff.com/',
        description: 'A light, floral IPA with classic fruity hops flavours',
        country: 'France',
        rating: 6.5,
        ABV: 5.6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Brune au Sapin',
        imageUrl: 'https://s.locavor.fr/data/produits/7/153370/200/pyrenees-55brune-au-sapin-33cl-153370-1618866806-1.png',
        brewery: 'Les Bières De Belleville',
        breweryLink: 'https://locavor.fr/presentation/5816-les-bieres-de-belleville',
        description: 'Table IPA beer. Fruity aromas (citrus, exotic fruits) and with a nice bitterness at 4,5°Alc/Vol. Brewed in Paris in the 20th district, rue Jean-Baptiste Dumay. The malt used for its manufacture is organic.',
        country: 'France',
        rating: 6.5,
        ABV: 4.5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'La Forge',
        imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fespritfermes.com%2Fstorage%2Fproducts%2FikpJV2RJVjAXI2jfju2hghrqgXH0Z6C5seCiJqyx.png&f=1&nofb=1',
        brewery: 'La Republik des Mousses',
        breweryLink: 'https://lmksas.wixsite.com/republik-des-mousses/la-brasserie',
        description: 'A pure malt beer is a beer whose worth is obtained only from the starch of cereals without adding sugar other than for refermentation in the bottle in order to obtain a natural carbonation by the yeast present in the bottle, these are living beers.',
        country: 'France',
        rating: 6.5,
        ABV: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Hèroique',
        imageUrl: 'https://untappd.akamaized.net/photos/2021_07_19/fec7d83f2106bd6a0fb1c4e42c1af40d_640x640.jpg',
        brewery: 'Demory Paris',
        breweryLink: 'https://demoryparis.com/heroique-dipa/',
        description: 'Good French beer',
        country: 'France',
        rating: 5,
        ABV: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Intrépide IPA',
        imageUrl: 'https://untappd.akamaized.net/photos/2021_07_16/765a597cb35d19f797885b6efa1d5e91_640x640.jpeg',
        brewery: 'Demory Paris',
        breweryLink: 'https://demoryparis.com/heroique-dipa/',
        description: 'Great French IPA',
        country: 'France',
        rating: 6.5,
        ABV: 6.3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Aero Pale',
        imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP._Q-xO4oQ3tTZ7W1P-0ZrygAAAA%26pid%3DApi%26h%3D160&f=1',
        brewery: 'Brasserie 3ienchs',
        breweryLink: 'https://shop.3ienchs.com/',
        description: 'Fruity pineapple nose, a little bit resinous. In the mouth, it is more citrusy with a little bitterness. A nice thirst-quenching beer quite well balanced.',
        country: 'France',
        rating: 6,
        ABV: 5.5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'DDH Pale Ale',
        imageUrl: 'https://untappd.akamaized.net/photos/2021_07_17/8689ca113f8f6767d3dcc105c6e9fb29_640x640.jpg',
        brewery: 'Modest Beer',
        breweryLink: null,
        description: 'Amazing Irish Beer',
        country: 'Northern Ireland',
        rating: 7.5,
        ABV: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Gravitational Moonbeam',
        imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.5jFnLUcwnysrhC_aCCiHWAHaHa%26pid%3DApi%26h%3D160&f=1',
        brewery: 'Amundsen',
        breweryLink: 'https://www.amundsenbrewery.com/',
        description: 'Fantastic beer from Norway',
        country: 'Norway',
        rating: 8,
        ABV: 7.2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'Beer No; 003',
        imageUrl: 'https://cdn.shopify.com/s/files/1/2806/3046/products/IMG_20210510_125425_1024x1024@2x.jpg?v=1620727370',
        brewery: 'Small Awe Bullhouse Brew Co.',
        breweryLink: 'https://waterintobeer.co.uk/products/small-axe',
        description: 'Juicy and crisp in equal measure. Naked oats and wheat provide good body and a soft mouthfeel, letting the Mosaic and Chinook shine.',
        country: 'Northern Ireland',
        rating: 6.5,
        ABV: 4.3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'The Foxes Rock IPA',
        imageUrl: 'https://cdn.beeradvocate.com/im/c_beer_image.gif',
        brewery: 'Cumberland Brewing Company',
        breweryLink: 'https://cumberlandbrewing.com/',
        description: 'Hazy amber with an orange tinge & 0.25cm frothy, white head that\'s patchy. The nose is poor & bland with faint biscuit & earthy hops but little else. The taste was stronger with more hop bitterness, some pine & light floral touches on top of a light-medium, crisp & quite dry body with a floral bitterness that lingers at the end too.',
        country: 'England',
        rating: 5.5,
        ABV: 5.2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 1,
        name: 'CITRA IPA',
        imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.t1qZfee0hU7lBdBkpM7-VwHaHa%26pid%3DApi%26h%3D160&f=1',
        brewery: 'Open Gate Brewery',
        breweryLink: 'https://www.guinnessopengate.com/the-brewery',
        description: 'Surprising tatse',
        country: 'United States of America',
        rating: 6,
        ABV: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});

  },

  down: (queryInterface, Sequelize) => {
      return queryInterface.bulkDelete('IPAs', null, {});
  }
};
